var delay = 10; //Given in minutes

on("ready", function(){
    log("slideShow initalizing...");
    var intervalId = setInterval(send,delay*60000);
    //var intervalId = setInterval(send,3000); //Testing
});



function send(){
    var result = slides[Math.floor(Math.random()*slides.length)];
    sendChat("Sarenteth",result);
}

slides = ["Vigor is used for strong, fast attacks. These are done on instinct, and have little to no finesse to them. You see an opening, you hit it."
         ,"Vigor is damaged by anything that makes you tire, slow down, or weaken."
         ,"Meditation is used for carefully aimed, carefully considered attacks. These are the kinds of things where you wait for a specific opening and take it, not when you just take whatever comes up first."
         ,"Meditation is damaged by attacks that daze you, put you on your back foot, or don't give you time to think."
         ,"Passion is used for losing control and going after someone, regardless of the consequences. Berserkers are famed for this."
         ,"Passion is damaged by anything that forces you to calm down or reconsider your current position."
         ,"Serenity is used for tactics that require calm, cool, practiced movement."
         ,"Serenity is damaged by attempts to goad you into making some kind of fatal mistake."
         ,"Empathy is used for attacks that rely on understanding your opponent's quirks and weaknesses. These are about noticing something about the way your opponent is fighting and capitalizing on it."
         ,"Empathy is damaged by moves that try to trick you, showing a 'weakness' in order to make you overextend."
         ,"Will is used for attacks that rely more on understanding your own strengths and weaknesses, rather than your opponent's. If you understand a flaw in your defense and attack so as to prevent its exploitation, that is an act of will."
         ,"Will is damaged by attacks that distract you and prevent you from noticing your own mistakes."
         ,"Hope is the last resort, particularly of unskilled or desperate combatants. This is what you use when you're out of ideas, so you just pick a strategy and say 'Hope this works!'"
         ,"Hope is damaged when your last resort strategy fails."
         ,"Verity is a different kind of last resort from hope. This is what you use when you are fighting to kill, not to stay alive."
         ,"Verity is damaged when you are given hope of your own survival, because now you fight for your life rather than for your cause."
         ,"Fate and Choice operate in similar ways. If you are fated to win a combat, you can use Fate to further that. If you are fated to lose it, use Choice instead."
         ,"Fate is damaged if things are going counter to what your destiny says."
         ,"Choice is damaged if things are going as planned."
         ,"Vigor is used when coming up with things off the top of your head. This is particularly useful when you're more concerned with shooting down someone's arguments than supporting your own."
         ,"Vigor is damaged when you are forced to stop and think, to gather your thoughts, to plan ahead."
         ,"Meditation is for prepared statements and arguments that you've worked out ahead of time. If you can guess someone's points ahead of time, you can use this approach."
         ,"Meditation is damaged when someone throws you a curveball and your preparation proves useless."
         ,"Passion is used for impassioned arguments, when you let your feelings do the talking. There's not much in the way of higher-order thought or sound reasoning here, just an emotional appeal."
         ,"Passion is damaged when people calm you down and get you to think logically."
         ,"Serenity is for those times when getting emotional will get you in trouble. If you're coming at something with cold logic, throwing away feelings and looking at facts, use serenity."
         ,"Serenity is damaged when you get riled up, when people goad you into an emotional response."
         ,"Empathy is used for manipulating and reading people. When you try to figure out what someone really thinks, or when you say something because you know how they'll react, use empathy."
         ,"Empathy is damaged when your reads of people prove wrong, or when you are forced to focus on your own arguments instead."
         ,"Will is for maintaining a core, reasonable assessment of your own views and beliefs. This can be used to convince other people by explaining yourself with detail and conviction."
         ,"Will is damaged when you become unsure of yourself, or lose sight of the things you hold to be true."
         ,"Hope is used for making positive, uplifting arguments. Use this to get people to look on the bright side and keep going despite hardships."
         ,"Hope is damaged when your positive outlook is challenged or proved wrong, or when that happens to the people you were trying to help."
         ,"Verity is for cynical, pessimistic arguments. If you're trying to convince someone to act in their own best interest, use verity."
         ,"Verity is damaged when things turn out better than you expect, and your pessimism starts looking more like fatalism."
         ,"Only chumps pay full price without trying to barter."
         ,"Slower travel is safer travel."
         ,"When working together, each player rolls separately and the group decides whose roll to use."
         ,"At the end of a conflict you can choose to make your temporary scores permanent."
         ,"If you concede in a contest, the momentum pool is ignored and you narrate the results."
         ,"Simple failures don't hurt you, but they do allow your opponent to set a circumstance."
         ,"Critical failures give your opponent a Wyrd and then damage you."
         ,"Simple successes deal damage equal to the difficulty, and partial successes deal half that."
         ,"Critical successes can either deal damage equal to the roll or inflict a scar."
         ,"When rolling with advantage, all successes are critical successes and all failures are simple failures."
         ,"When rolling with disadvantage, all simple successes are partial successes and all failures are critical failures."
         ,"Obsessions let you push yourself, changing your approach's score to be whatever you just rolled. This costs one Wyrd."
         ,"Forcing other people to follow their obsessions is a great way to get Wyrd for yourself."
         ,"They aren't children."
         ,"You can always spend a Wyrd to flip the dice or to resolve an uncertainty. This costs one Wyrd."
         ,"You can narrate the result of a destiny anytime you like, as long as it fits the destined path. This costs one Wyrd."
         ,"You can invoke an ally to substitute one of their approaches for yours."
         ,"Magic is at its weakest during the night of the full moon. Plan accordingly."
         ,"The Law of Hospitality is inviolate."
         ,"Fairies can use favors as a sympathy for their magic."
         ,"Circles aren't required for summoning, but they are recommended."
         ,"Content warning: body horror, violence, whimsy."
         ,"It's right behind you."
         ,"Clams are apparently quite skilled at digging dungeons."
         ,"Wheat: Here & Now"
         ,"You can always bribe players (or the GM) with Wyrd."
         ,"Water, fire, silver, and the presence of the moon all dampen magic."
         ,"Fairies grow stronger and stranger when out of direct sunlight."
         ,"All humans are just dwarves <i>wearing masks</i>."
         ,"Remember this: Fairies don't really exist. They're just a collective hallucination."
         ,"If you mind-boop a spirit, it will mind-boop you right into a coma."
         ,"I'm sure everything is just as it appears."
         ,"...Did you hear that?"
         ,"The White Shade is coming."
         ,"Stones in the mouth can prevent a corpse from rising again."
         ,"Piling stones on a grave can keep a revenant at bay... For a time."
         ,"A circle of salt can do wonders."
         ,"The GM always lies."
         ,"Remember, this game is still being playtested. If you have comments or criticisms, I'd love to hear them."
         ,"Remember, I'm always looking for feedback. Message me, email me, whatever, just get it to me!"
         ,"Do you hear what I hear?<br><br>Do you see what I see?"
         ,"Elves are wonderful. They provoke wonder.<br>Elves are marvelous. They cause marvels.<br>Elves are fantastic. They create fantasies.<br>Elves are glamorous. They project glamor.<br>Elves are enchanting. They weave enchantment.<br>Elves are terrific. They beget terror.<br><br>The thing about words is that meanings can twist just like a snake, and if you want to find snakes, look behind words that have changed their meaning.<br><br>No one ever said elves are nice.<br>Elves are <b>bad</b>."
         ,"Tall and proud and wondrous fair<br>The people of the dark and air<br>Hold high the iron that they fear<br>When the Fair Folk call,<br>don't let them near..."
         ,"Content warning: body horror, violence, existentialism, whimsy."
         ,"None of it matters."
         ,"You hear a distant chirping..."
         ,"You hear howling in the distance."
         ,"We did this."
         ,"At least it's not a dragon."
         ,"You can do this. You're strong enough."
         ,"Everything has a history. Use it to your advantage."
         ,"Give a thing a name and you solidify its place in the world. Give a thing a place in the world and you have power over it."
         ,"History often repeats itself. Use that to your advantage."
         ,"The familiar's bond is a powerful one, and not something to be entered into lightly."
         ,"There's always the Crossroads."
         ,"Forests aren't supposed to move."
         ,"Don't you just want to be perfect?"
         ,"That which creates itself must be God."
         ,"Within every pebble is a statue."
         ,"They seem nice."
         ,"The woods are just so inspiring!"
         ,"For magic to have an effect, you must not only succeed on the die roll but also knock out the Environment score."
         ,"Every sympathy, ritual, and advantage can be made into another point of mana for your magic."
         ,"Tors place great stock in reading the signs left in the stars, for as it is in the heavens, so it is on the earth."
         ,"Mairs place great stock in reading the entrails of beasts or the shapes of nearly-fatal scars, for so does King Crow speak."
         ,"Irdans place great stock in reading the bones of beasts and/or witches, for these cling long to life."
         ,"It's right behind you."
         ,"It's right in front of you."
         ,"What is that?"
         ,"Do birds understand friendship?"
         ,"Sie sind keine Kinder."
         ,"Does 'Goatherd' count for stuff from the Between?"
         ,"You can gain a prop that is relevant to one of your edges by spending a Wyrd."
         ,"The deer are screaming."
         ,"'Tis better not to pray\nthan too much offer;\na gift ever looks to a return.\n'Tis better not to send\nthan too much consume."
         ,"Did Aelstan really die for this?"
         ,"How did it come to this?"
         ,"Was this fated?"
         ,"It is impossible to break the strands of destiny."
         ,"Destiny is a construct, and nothing more."
         ,"Burn for you are tinder,\nBleed for I am thirsty,\nBurst for my sorrow,\nSuffer for my friend."
         ,"Did you know that, much like trees, druids reproduce by budding?"
         ,"You can offer to use a scar to double the difficulty of your roll, in exchange for a wyrd."
         ,"Welcome all you wayward souls,\n   you who wander in the dark,\nthere's light for the lost,\n   the forlorn and the meek,\nin the final tolling knell.\n   All forgotten are your sorrows,\nWhen you to soil of earth\n   submit."
         ,"<b>Achievement Get</b>But Not Yet - <i>Brett</i><br>Never Tell Me The Odds - <i>Charlie</i><br>Life, Uh, Finds A Way - <i>Charlie, Brett</i><br>A Wizard Is Never Late - <i>Kegan, Luke</i><br>Mother Was A Hamster - <i>Kegan</i><br>Game Over, Man - <i>Brett, Kegan</i><br>Spared No Expense - <i>Charlie</i><br>Howling In The Distance - <i>Charlie</i><br>Get On With It - <i>Graham, Thomas, kyle, Luke, Brett, Charlie, Kegan, Joschi</i><br>Put On The Glasses - <i>Graham, Charlie</i><br>We All Float Down Here - <i>Kegan</i>"
         ,"Stupidity is glory if you win!"
         ,"Charlie wields wanton destruction the way a three-year-old wields a Caprisun: with reverence but also with fruit punch."
         ,"The Man in the Red Cloak laughs"
         ,"You can't swing a bag of chickens you ain't got."
         ,"The fear penalty is the minimum by which you must increase the difficulty when you escalate."
         ,"I say we follow the chicken."
         ,"I don't know nothin' about no stitching."
         ,"Darkness has two syllables. Merrick has two syllables. This is not a coincidence."
         ,"Joschi takes 3d6 fall damage."
         ,"Kegan takes 3d6 fall damage."
         ,"Thomas takes 3d6 fall damage."
         ,"Graham takes 3d6 fall damage."
         ,"Kyle takes 3d6 fall damage."
         ,"Brett takes 3d6 fall damage. Git gud."
         ,"Luke takes 3d6 fall damage."
         ,"Charlie takes 3d6 fall damage."
         ];
